name: we_the_future
description: A civic education app for young Americans to learn, engage, and act.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/satoshi/Satoshi-Regular.ttf
        - asset: fonts/satoshi/Satoshi-Medium.ttf
          weight: 500
        - asset: fonts/satoshi/Satoshi-Bold.ttf
          weight: 700
        - asset: fonts/satoshi/Satoshi-Light.ttf
          weight: 300
        - asset: fonts/satoshi/Satoshi-Black.ttf
          weight: 900
